version: 'Build #{build}'
image: Visual Studio 2017
configuration:
- Store
- Release
- Debug
platform: x86

before_build:
- ps: .\update-version.ps1

build:
  parallel: true
  project: TranslucentTB.sln

after_build:
- ps: .\create-installer.ps1

test: off

artifacts:
- path: $(CONFIGURATION)
  name: Raw build artifacts
- path: TranslucentTB-setup.exe
  name: Desktop Installer
- path: StorePackage\AppPackages
  name: Store App Package

deploy:
  provider: GitHub
  description: 'TODO: Fill this'
  draft: true
  artifact: Desktop Installer,$(CONFIGURATION)\*.pdb
  auth_token:
    secure: KofMs1LM/RjB79NyxThnuOxkUUZxaN98cJdRJepe9ZIwf4/5nxMi+cNiZVe83QxD
  on:
    configuration: Release
    appveyor_repo_tag: true