version: 'Build #{build}'
image: Visual Studio 2019 Preview
configuration:
- Release
- Debug
platform:
- x86
- x64
- ARM
- ARM64

before_build:
- ps: .\update-version.ps1

build:
  parallel: true
  project: TranslucentTB.sln

test: off

artifacts:
- path: $(PLATFORM)\$(CONFIGURATION)
  name: Raw build artifacts
- path: $(PLATFORM)\$(CONFIGURATION)\*.pdb
  name: Debug symbols
- path: AppPackage\AppPackages
  name: App packages