version: 'Build #{build}'
image: Visual Studio 2017
configuration:
- Store
- Release
- Debug
platform: x86
before_build:
- ps: .\update-version.ps1
build:
  parallel: true
test: off
artifacts:
- path: $(CONFIGURATION)
  name: Build artifacts
- path: StorePackage\AppPackages
  name: App packages
deploy: off