version: Build #{build}
image: Visual Studio 2019
configuration:
- Release
- Debug
platform:
- x86
- x64
- ARM
- ARM64

install:
- vcpkg install --triplet %PLATFORM%-windows detours gtest rapidjson fmt spdlog
- vcpkg install wil:%PLATFORM%-windows --head

before_build:
- ps: .\update-version.ps1

build:
  parallel: true
  project: TranslucentTB.sln

test_script:
- $(PLATFORM)\$(CONFIGURATION)\Tests.exe --gtest_output=xml:tests.xml

after_test:
- ps: Invoke-WebRequest -Uri "https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID" -Method Put -Infile tests.xml

cache:
- C:\tools\vcpkg\installed

artifacts:
- path: $(PLATFORM)\$(CONFIGURATION)
  name: Raw build artifacts
- path: $(PLATFORM)\$(CONFIGURATION)\*.pdb
  name: Debug symbols
- path: AppPackage\AppPackages
  name: App packages